openapi: 3.0.0

info:
  title: helpful-neighbors
  description: REST API for Helpful Neighbors https://www.helpourneighbors.com/. Uses API Key Authorization.
  version: 2019-11-07

paths:

  /emails:
    post:
      summary: Send an email.
      operationId: SendEmail
      description: Send an email.
      tags:
      - email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmail'
      responses:
        '201':
          description: email response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailResponse'
                
  /listings/{id}:
    delete:
      summary: Delete a listing
      operationId: DeleteListing
      description: Deletes a listing if a valid secret_token is provided
      tags:
      - listing
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/secret_token'
      responses:
        '200':
          description: listing delete response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadListing'
        '400':
          description: Invalid secret_token provided to delete listing.
        '404':
          description: The listing does not exist.

    post:
      summary: Create an Listing.
      operationId: CreateListing
      description: Create an Listing
      tags:
      - listing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateListing'
      responses:
        '201':
          description: listing response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
                
  /listings/offer:
    get:
      summary: Returns a paginated array of listings. Use nextToken to get next page.
      operationId: ReadListingOffers
      description: Returns a paginated array of listings. Use nextToken to get next page.
      tags:
      - listing
      parameters:
        - $ref: '#/components/parameters/next_token'
        - $ref: '#/components/parameters/state_filter'
      responses:
        '200':
          description: paginated array of listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaginatedListings'
  
  /listings/request:
    get:
      summary: Returns a paginated array of listings. Use nextToken to get next page.
      operationId: ReadListingRequests
      description: Returns a paginated array of listings. Use nextToken to get next page.
      tags:
      - listing
      parameters:
        - $ref: '#/components/parameters/next_token'
        - $ref: '#/components/parameters/state_filter'
      responses:
        '200':
          description: paginated array of listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaginatedListings'

components:
  parameters:
    id:
      name: id
      in: path
      description: Identifier of listing
      required: true
      example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
      schema:
        type: string
        format: uuid
    secret_token:
      name: secret_token
      in: query
      description: secret token used to delete a listing
      required: true
      example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
      schema:
        type: string
        format: uuid
    next_token:
      name: next_token
      in: query
      description: pagination token
      required: false
      example: offer
      schema:
        type: string
    type_filter:
      name: type_filter
      in: query
      description: type of a listing
      required: false
      example: offer
      schema:
        type: string
    state_filter:
      name: state_filter
      in: query
      description: state a listing is in
      required: false
      example: VIC
      schema:
        type: string
    
  schemas:
    
    SendEmail:
      description: SendEmail payload.
      type: object
      required:
        - listingId
        - fromEmail
        - message
      properties:
        listingId:
          type: string
          format: uuid
          description: Listing identifier.
          example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
        fromEmail:
          type: string
        message:
          type: string
        name:
          type: string
          
    EmailResponse:
      description: SendEmail payload.
      type: object
      required:
        - listingId
        - to_email
        - from_email
        - message
        - name
        - timestamp
        - mailgun_id
        - mailgun_message
      properties:
        listingId:
          type: string
          format: uuid
          description: Listing identifier.
          example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
        to_email:
          type: string
        from_email:
          type: string
        message:
          type: string
        name:
          type: string
        timestamp:
          format: date-time
          description: The timestamp the email was sent
        mailgun_id:
          type: string
        mailgun_message:
          type: string
  
    Listing:
      description: Listing.
      type: object
      required:
        - id
        - message
        - latitude
        - longitude
        - postcode
        - listingState
        - name
        - timestamp
        - email
        - listingType
        - address
        - country
      properties:
        id:
          type: string
          format: uuid
          description: Listing identifier.
          example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
        email:
          type: string
        message:
          type: string
        latitude:
          type: string
          example: "-37.840935"
        longitude:
          type: string
          example: "144.946457"
        postcode:
          type: string
          example: "3000"
        listingState:
          type: string
          example: VIC
        address:
          type: string
        country:
          type: string
        listingType:
          type: string
        name:
          type: string
        timestamp:
          format: date-time
          description: The timestamp the listing was created
        secretToken:
          type: string
          format: uuid
          description: Token used to delete a listing
          example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
    
    ReadListing:
      description: Listing response. Email is not returned.
      type: object
      required:
        - id
        - message
        - latitude
        - longitude
        - postcode
        - listingState
        - name
        - timestamp
        - listingType
        - country
      properties:
        id:
          type: string
          format: uuid
          description: Listing identifier.
          example: 1ce90bf8-2029-49dc-8aa6-d959ce92fa9b
        message:
          type: string
        latitude:
          type: string
          example: "-37.840935"
        longitude:
          type: string
          example: "144.946457"
        postcode:
          type: string
          example: "3000"
        listingState:
          type: string
          example: VIC
        listingType:
          type: string
        country:
          type: string
        name:
          type: string
        timestamp:
          format: date-time
          description: The timestamp the listing was created
          
    PaginatedListings:
      description: PaginatedListings.
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ReadListing'
        nextToken:
          type: string
          example: null
          nullable: true
          description: null when there are no more items to fetch
      
    CreateListing:
      description: Payload to create a Listing.
      type: object
      required:
        - email
        - message
        - latitude
        - longitude
        - postcode
        - listingState
        - name
        - listingType
        - address
        - country
      properties:
        email: 
          type: string
        message:
          type: string
        latitude:
          type: string
          example: "-37.840935"
        longitude:
          type: string
          example: "144.946457"
        postcode:
          type: string
          example: 3000
        listingState:
          type: string
          example: VIC
        address:
          type: string
        country:
          type: string
        listingType:
          type: string
        name:
          type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey 
      in: header
      name: X-API-KEY

security:
  - ApiKeyAuth: [${apiKey}]